services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["sh", "-c", "alembic upgrade head && uvicorn --host 0.0.0.0 --port 8000 app.main:app --root-path /api"]
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgress@db/postgres
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
