apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-backend
  labels:
    app: {{ include "app.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
        tier: backend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8000
          env:
              {{- range $key, $value := .Values.backend.env }}
              - name: {{ $key }}
                value: {{ $value | quote }}
              {{- end }}
