apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ include "app.name" . }}
    tier: backend