apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "app.name" . }}
    tier: frontend