apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-nginx
spec:
  selector:
    app: {{ include "app.name" . }}-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
