apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "app.name" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "app.fullname" . }}-nginx-config
