postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: db
  primary:
    persistence:
      enabled: true
      size: 1Gi
  primary:
    nodeSelector:
      kubernetes.io/arch: arm64

frontend:
  image:
    repository: mcleantom/fastapi-helm-frontend
    tag: latest

backend:
  image:
    repository: mcleantom/fastapi-helm-backend
    tag: latest
  env:
    DATABSE_URL: "postgres://postgress:postgress@test-postgresql:5432/db"