postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: db
  primary:
    persistence:
      enabled: true
      size: 1Gi
  primary:
    nodeSelector:
      kubernetes.io/arch: arm64

frontend:
  image:
    repository: mcleantom/fastapi-helm-frontend
    tag: latest
  imagePullPolicy: Always

backend:
  image:
    repository: mcleantom/fastapi-helm-backend
    tag: latest
  imagePullPolicy: Always
  env:
    DATABASE_URL: "postgresql://postgres:postgres@test-postgresql:5432/db"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: grafana
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: test.athenaracing.tech